variables:
- group: 'project variables - prod'

stages:
  - stage: TestCLI
    jobs:
      - job: TestCLI
        steps:
          - task: AzureCLI@1
            displayName: 'Test command'
            inputs:
              azureSubscription: 'AZ-RG-CS-MW-ACE-NA-Sandbox-01'
              scriptLocation: inlineScript
              inlineScript: |
                echo 'test : ${{length($(azureAppServiceSlot))}}'