steps:
  - task: DeleteFiles@1
    displayName: 'Cleaning before artifact ziping'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        .git
        .gitignore
        README.md
        .storybook
        build
        azure-pipelines
        azure-pipelines.yml
        .editorconfig
        .eslintrc.yml
        .stylelintrc
