parameters:
  runCheckQuality: true

steps:
  - task: CacheBeta@0
    inputs:
        key: npm | $(Agent.OS) | package-lock.json
        path: '$(NPM_CONFIG_CACHE)'
    displayName: Cache npm

  - task: Npm@1
    displayName: 'Npm ci'
    inputs:
        command: 'ci'

  - ${{ if eq(parameters.runCheckQuality, true) }}:
    - template: check-quality-steps.yml

  - task: Npm@1
    displayName: 'Npm run export'
    inputs:
        command: 'custom'
        customCommand: 'run export'
