parameters:
  tagLabel: ''
  commit: ''

jobs:
  - job: GitTagging

    steps:
      - checkout: self
        persistCredentials: true

      - bash: |
          echo "Tagging commit: $commit with label: $tagLabel"
          git -c http.extraheader="AUTHORIZATION: bearer $systemAccessToken" tag $tagLabel $commit
          git -c http.extraheader="AUTHORIZATION: bearer $systemAccessToken" push origin $tagLabel
        env:
          tagLabel: ${{parameters.tagLabel}}
          commit: ${{parameters.commit}}
          systemAccessToken: $(system.accesstoken)
        failOnStderr: false
