parameters:
  environment: ''
  azureSubscription: ''
  azureAppService: ''
  azureAppServiceSlot: ''

jobs:
  - deployment: StaticDeploy
    environment: '${{parameters.environment}}'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: static-${{parameters.artifactSuffix}}

            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy to WebApp'
              condition: eq(parameters.azureAppServiceSlot, '')
              inputs:
                azureSubscription: '${{parameters.azureSubscription}}'
                WebAppName: '${{parameters.azureAppService}}'
                ResourceGroupName: '${{parameters.azureSubscription}}'
                packageForLinux: '$(Pipeline.Workspace)/static-${{parameters.artifactSuffix}}/*-static-${{parameters.artifactSuffix}}.zip'

            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy to WebApp slot'
              condition: ne(parameters.azureAppServiceSlot, '')
              inputs:
                azureSubscription: '${{parameters.azureSubscription}}'
                WebAppName: '$(${{parameters.azureAppService}})'
                deployToSlotOrASE: true
                ResourceGroupName: '${{parameters.azureSubscription}}'
                SlotName: '${{parameters.azureAppServiceSlot}}'
                packageForLinux: '$(Pipeline.Workspace)/static-${{parameters.artifactSuffix}}/*-static-${{parameters.artifactSuffix}}.zip'
