parameters:
  environment: ''
  azureSubscription: ''
  azureAppService: ''
  azureAppServiceSlot: ''
  azureCdnProfile: ''
  azureCdnEndpoint: ''

jobs:
  - deployment: SwapAndPurgeCdn
    environment: '${{parameters.environment}}'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@1
            displayName: 'Swap with production'
            inputs:
              azureSubscription: '${{parameters.azureSubscription}}'
              scriptLocation: inlineScript
              inlineScript: 'az webapp deployment slot swap --slot "${{azureAppServiceSlot}}" --name "${{azureAppService}}" --resource-group "${{azureSubscription}}"'

          - task: AzureCLI@1
            displayName: 'Purge CDN'
            inputs:
              azureSubscription: '${{parameters.azureSubscription}}'
              scriptLocation: inlineScript
              inlineScript: 'az cdn endpoint purge -g "${{azureSubscription}}" -n "${{azureCdnEndpoint}}" --profile-name "${{azureCdnProfile}}" --content-paths ''/*'''

