parameters:
  inputFolderOrFile: ''
  compressedFileName: ''
  artifactName: ''

steps:
  - task: ArchiveFiles@2
    displayName: 'Zip artifact'
    inputs:
      rootFolderOrFile: '${{parameters.inputFolderOrFile}}'
      archiveFile: '$(Build.ArtifactStagingDirectory)/${{parameters.compressedFileName}}.zip'
      includeRootFolder: false

  - publish: '$(Build.ArtifactStagingDirectory)/${{parameters.compressedFileName}}.zip'
    artifact: ${{parameters.artifactName}}
