parameters:
  artifactSuffix: ''

steps:
  - download: current
    artifact: ssr

  - task: ExtractFiles@1
    displayName: 'Unzip SSR artifact'
    inputs:
      archiveFilePatterns: '$(Agent.BuildDirectory)/ssr/*.zip'
      destinationFolder: '$(System.DefaultWorkingDirectory)/temp'

  - task: CacheBeta@0
    inputs:
      key: npm | $(Agent.OS) | package-lock.json
      path: $(npm_config_cache)
    displayName: Cache npm

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'ci'
      customRegistry: useFeed
      customFeed: 'e930196b-b800-4fa1-9199-26acc5ef6b00'

  - task: Npm@1
    displayName: 'NPM export'
    inputs:
      command: 'custom'
      customCommand: 'run export'

  # - task: DeleteFiles@1
  #   displayName: 'Delete web.config from static folder'
  #   inputs:
  #     Contents: out/static/web.config
  #   continueOnError: true

  - template: compress-and-publish-steps.yml
    parameters:
      inputFolderOrFile: '$(System.DefaultWorkingDirectory)/out'
      compressedFileName:  '$(Build.BuildId)-static-${{parameters.artifactSuffix}}'
      artifactName: 'static-${{parameters.artifactSuffix}}'
