trigger: none

variables:
  dnsZoneName: 'aceteam.tech'
  azureSubscription: 'AZ-RG-CS-MW-ACE-NA-Prod-01'
  cname: 'hosted-login'
  azureAppAddress: 'janrain-hosted-login-poc.azurewebsites.net'

stages:
  - stage: CustomDomainCreatAssign
    jobs:
      - job: CustomDomainCreatAssign
        steps:
          - task: AzureCLI@1
            displayName: 'Create subdomain'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptLocation: inlineScript
              inlineScript: |
                az network dns record-set cname create \
                  --name $(cname) \
                  --resource-group $(azureSubscription) \
                  --ttl 60 \
                  --zone-name $(dnsZoneName) &&
                az network dns record-set txt create \
                  --name 'asuid.$(cname)' \
                  --resource-group $(azureSubscription) \
                  --ttl 60 \
                  --zone-name $(dnsZoneName)

          - task: AzureCLI@1
            displayName: 'Assign subdomain'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptLocation: inlineScript
              inlineScript: |
                az network dns record-set cname set-record \
                  --cname $(azureAppAddress) \
                  --record-set-name $(cname) \
                  --resource-group $(azureSubscription) \
                  --ttl 60 \
                  --zone-name $(dnsZoneName) &&
                az network dns record-set txt add-record \
                  --record-set-name 'asuid.$(cname)' \
                  --resource-group $(azureSubscription) \
                  --value '0EA78F994347170E787D23F2FF0EA8FE68B6FCDB3FCAE90B185649D0102ED0D3' \
                  --zone-name $(dnsZoneName)
