trigger:
  - none

variables:
- group: 'project variables - ephemeral'

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

extends:
  template: pr-preview.yml@templates
