# For Azure Dev Ops PR trigger needs to be configured in GUI
trigger: none

# pr:
#   branches:
#     include:
#     - master
#   paths:
#     exclude:
#     - README.md

stages:
  - stage: VerifyPR
    variables:
      - name: NPM_CONFIG_CACHE
        value: $(Pipeline.Workspace)/.npm
      - group: 'us.aceteam.tech - application - prod'

    jobs:
      - job: NextExport
        displayName: Lint, Unit and Export Testing
        steps:
          - template: templates/steps/run-next-export-steps.yml

      - job: AccessibilityTesting
        displayName: Accessibility Testing
        steps:
          - template: templates/steps/run-next-export-steps.yml
            parameters:
              runCheckQuality: false
          - template: templates/steps/check-a11y-steps.yml

      - job: E2ETesting
        displayName: End-to-End Testing
        steps:
          - template: templates/steps/run-next-export-steps.yml
            parameters:
              runCheckQuality: false
          - template: templates/steps/check-e2e-steps.yml


