pr:
  - master
  paths:
    exclude:
      README.md

steps:
  - task: Yarn@3
    displayName: 'Yarn install'
    inputs:
      Arguments: install

  - task: Yarn@3
    displayName: 'Yarn export'
    inputs:
      Arguments: export
