trigger:
- master

variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm

stages:
  - stage: SsrBuild
    jobs:
      - template: templates/job/ssr-build-job.yml

  - stage: SsrDeploy_Preview
    dependsOn: SsrBuild
    jobs:
      - template: templates/job/ssr-deploy-job.yml
        parameters:
          environment: 'preview'
          azureSubscription:  'AZ-RG-CS-MW-ACE-NA-NonProd-01'
          applicationVariableGroup: 'us.aceteam.tech - application - prod'
          azureAppServiceName: 'preview-aceteam-tech-en-us'
