trigger:
- master

variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  subscription: 'AZ-RG-CS-MW-ACE-NA-Sandbox-01'
  sppService: 'akamai-hosted-login-poc'

stages:
  - stage: StaticBuild
    jobs:
      - template: templates/job/static-build-job.yml
        parameters:
          artifactSuffix: 'akamai'
          applicationVariableGroup: 'hosted-login.aceteam.tech - application - prod'

  - stage: DeployAkamai
    dependsOn: StaticBuild
    jobs:
      - template: templates/job/static-deploy-job.yml
        parameters:
          artifactSuffix: 'akamai'
          azureSubscription: '$(subscription)'
          environment: 'akamai'
          azureAppService: '$(sppService)'
