trigger:
  - master

variables:
- group: 'project variables - prod'

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

extends:
  - template: static-prod.yml@templates
    parameters:
      variableGroup:
        variables:
          - group: $(applicationVariableGroup)
      projectVariables:
        serviceConnectionName: $(serviceConnectionName)
        appService: $(appService)
        artifactSuffix: $(artifactSuffix)
        environment: $(environment)
