trigger:
  - master

variables:
- group: 'project variables - prod'
- group: '$(applicationVariableGroup)'

resources:
  repositories:
  - repository: templates
    type: git
    name: ACE-Website/pipelines-repo

extends:
  template: static-prod.yml@templates
  parameters:
    projectVariables:
      serviceConnectionName: $(serviceConnectionName)
      appService: $(appService)
      artifactSuffix: $(artifactSuffix)
      environment: $(environment)
