trigger:
- master

variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  azureProdSubscription: 'AZ-RG-CS-MW-ACE-NA-Prod-01'
  azureProdAppService: 'aceteam-tech-en-us'

stages:
  - stage: StaticBuild
    jobs:
      - template: templates/job/static-build-job.yml
        parameters:
          artifactSuffix: 'prod'
          applicationVariableGroup: 'us.aceteam.tech - application - prod'

  - stage: DeployTest
    dependsOn: StaticBuild
    jobs:
      - template: templates/job/static-deploy-job.yml
        parameters:
          artifactSuffix: 'prod'
          azureSubscription: '$(azureProdSubscription)'
          environment: 'test'
          azureAppService: '$(azureProdAppService)'
          azureAppServiceSlot: 'test'

  - stage: PromoteToProd
    dependsOn: DeployTest
    jobs:
      - template: templates/job/swap-and-purge-cdn-job.yml
        parameters:
          environment: 'prod'
          azureSubscription: '$(azureProdSubscription)'
          azureAppService: '$(azureProdAppService)'
          azureAppServiceSlot: 'test'
          azureCdnProfile: 'aceteamtech-CDN'
          azureCdnEndpoint: 'aceteamtech-en-us'

  - stage: TagRelease
    dependsOn: PromoteToProd
    jobs:
      - template: templates/job/git-tag-job.yml
        parameters:
          tagLabel: 'release/$(Build.BuildNumber)'
          commit: '$(Build.SourceVersion)'
