trigger:
  - master

variables:
  - group: 'project variables - prod'

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

stages:
  - template: static-prod.yml@templates
    parameters:
      projectVariables:
        serviceConnectionName: $[variables.serviceConnectionName]
        appService: $[variables.appService]
        applicationVariableGroup: $[variables.applicationVariableGroup]
        artifactSuffix: $[variables.artifactSuffix]
        environment: $[variables.environment]
