trigger:
- master

variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
  subscription: 'AZ-RG-CS-MW-ACE-NA-NonProd-01'
  sppService: 'janrain-hosted-login-poc'

stages:
  - stage: StaticBuild
    jobs:
      - template: templates/job/static-build-job.yml
        parameters:
          artifactSuffix: 'janrain'
          applicationVariableGroup: 'us.aceteam.tech - application - prod'

  - stage: DeployJanrain
    dependsOn: StaticBuild
    jobs:
      - template: templates/job/static-deploy-job.yml
        parameters:
          artifactSuffix: 'janrain'
          azureSubscription: '$(subscription)'
          environment: 'janrain'
          azureAppService: '$(sppService)'
          azureAppServiceSlot: 'janrain'
