trigger:
  - master

variables:
- group: 'project variables - prod'

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

stages:
  - stage: Check variable
    jobs:
      - job:  Check variable
        steps:
        - script: echo $(applicationVariableGroup)

  - template: static-prod.yml@templates
    parameters:
      projectVariables:
        serviceConnectionName: $(serviceConnectionName)
        appService: $(appService)
        applicationVariableGroup: $(applicationVariableGroup)
        artifactSuffix: $(artifactSuffix)
        environment: $(environment)
