trigger:
  - master

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

stages:
  variables:
    - group: 'project variables - prod'

  - template: static-prod.yml@templates
    parameters:
      projectVariables:
        serviceConnectionName: $(serviceConnectionName)
        appService: $(appService)
        applicationVariableGroup: $(applicationVariableGroup)
        artifactSuffix: $(artifactSuffix)
        environment: $(environment)
