trigger: none

variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm

stages:
  - stage: StaticBuild
    jobs:
      - template: templates/job/static-build-job.yml
        parameters:
          artifactSuffix: 'sit'
          applicationVariableGroup: 'us.aceteam.tech - application - sit'

  - stage: DeployTest
    dependsOn: StaticBuild
    jobs:
      - template: templates/job/static-deploy-job.yml
        parameters:
          artifactSuffix: 'sit'
          environment: 'sit'
          azureSubscription: 'AZ-RG-CS-MW-ACE-NA-NonProd-01'
          azureAppService: 'sit-aceteam-tech-en-us'
