trigger:
  - master

variables:
- group: 'project variables - <environment>'
- group: '<domain> - application - <environment>'

resources:
  repositories:
  - repository: templates
    type: git
    name: MW-Framework/MW-azure-pipelines

extends:
  template: ssr-prod.yml@templates
